version: '3'
services:
  redpanda:
    image: vectorized/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
  console:
    image: vectorized/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          messagePack:
            enabled: true
            topicNames: ["/.*msgpack.*/"]
    ports:
      - 22222:8080
    depends_on:
      - redpanda
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=marketDb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3310:3306'
    volumes:
      - db:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:6.0.10-alpine
    ports:
      - '6379:6379'
volumes:
  db:
    driver: local
  cache:
    driver: local
